name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible
      - name: Render Ansible Inventory
        run: |
          ansible localhost -m template -a "src=ansible/inventory/inventory.yaml.j2 dest=ansible/inventory/inventory.yaml"
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      - name: Output SSH key to file
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Deploy with Ansible
        run: |
          ansible-playbook -i ansible/inventory/inventory.yaml ansible/playbook/playbook.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
